server:
  port: 2211

spring:
  application:
    name: book-my-ticket

  datasource:
    url: jdbc:mysql://localhost:3306/Book-My-Ticket?createDatabaseIfNotExist=true
    username: root
    password: Maalu@1921

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      url: redis://localhost:6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: zayedzahi122@gmail.com
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

admin:
  email: admin@gmail.com
  password: admin1234
cloudinary:
  url: ${CLOUDINARY_URL}